<?php
get_header();
get_template_part('templates/banner');
get_template_part('templates/about');
get_template_part('templates/services');
get_template_part('templates/portfolio');
get_template_part('templates/contact');
get_template_part('templates/call');
get_footer();
?>